FROM python:3.11-slim

WORKDIR /app

# Copier le fichier requirements.txt
COPY requirements.txt .

# Copier le fichier Python correspondant au service "car"
COPY cars_service.py .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "cars_service:app", "--host", "0.0.0.0", "--port", "8002"]
